# Generated by Django 2.2.6 on 2020-03-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('RestaurantId', models.IntegerField(db_column='Restaurant ID', primary_key=True, serialize=False)),
                ('RestaurantName', models.CharField(db_column='Restaurant Name', max_length=250)),
                ('Cuisines', models.CharField(blank=True, max_length=350)),
                ('AverageCostForTwo', models.IntegerField(blank=True, db_column='Average Cost for two')),
                ('Currency', models.CharField(blank=True, max_length=100)),
                ('HasTableBooking', models.BooleanField(blank=True, db_column='Has Table booking')),
                ('HasOnlineDelivery', models.BooleanField(blank=True, db_column='Has Online delivery')),
                ('AggregateRating', models.DecimalField(blank=True, db_column='Aggregate rating', decimal_places=2, default=0, max_digits=4)),
                ('RatingColor', models.CharField(blank=True, db_column='Rating color', max_length=50)),
                ('RatingText', models.CharField(blank=True, db_column='Rating text', max_length=50)),
                ('Votes', models.IntegerField(blank=True)),
            ],
            options={
                'ordering': ['Votes'],
            },
        ),
    ]
