# Generated by Django 2.2.6 on 2020-03-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='AggregateRating',
            field=models.FloatField(blank=True, db_column='Aggregate rating'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='HasOnlineDelivery',
            field=models.CharField(blank=True, db_column='Has Online delivery', max_length=10),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='HasTableBooking',
            field=models.CharField(blank=True, db_column='Has Table booking', max_length=10),
        ),
    ]
