# Generated by Django 2.2.6 on 2020-03-30 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200330_0737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['AggregateRating']},
        ),
    ]
